### ISSUE TITLE
simulation/mars/sim package not in master 18.09

### ISSUE THREAD

**Issue by Rauldg** [rock-core/rock-osdeps-package_set#2]
In the 18.01 version of the release simulation/mars/sim was included, but not in the 18.09 release. Is this intentional? 

@2maz

**Comment by Rauldg** [comment]
The master version of `simulation/mars/sim` is not compatible with the dependencies available from the binaries.

**Comment by 2maz** [comment]
> In the 18.01 version of the release simulation/mars/sim was included, but not in the 18.09 release. Is this intentional?

No.  But there have been build errors occuring in 18.09 which could not or just were not fixed due to limited maintenance power. 
However, I have been just looking in the missing support and am in the process of adding simulation/mars/sim and simulation/mars/app into the release master-18.09.

> The master version of simulation/mars/sim is not compatible with the dependencies available from the binaries.

Should be no surprise: simulation is taken from a single repo and only submodules have been rendered successfully into Debian packages  - which I am in the process of fixing. 
If you pin the source packages to the state of  the commit provided in the mars-simulation-* changelog you should be fine though.

**Comment by 2maz** [comment]
I added the packages. Could try using the branch 'test' for the rock-osdeps-package_set with a clean workspace.
Using the following setting in your manifest should do:
```
- rock-osdeps:
  type: git
  url: git@github.com:rock-core/rock-osdeps-package_set.git
  branch: test

layout:
- mars/simulation/app
```

**Comment by Rauldg** [comment]
Tested on a fresh installation and works. I will now try it with the software around it (e.g. orogen component).

**Comment by Rauldg** [comment]
@2maz The binary version that you provide seems to be incompatible with the master version of the orogen component, [here is the output of an installation that combines them](http://bob.dfki.uni-bremen.de:8080/job/docker-ade/IMAGE_NO=ubuntu%3A18.04/50/console). 

Should I expect a compatible debian binary of the orogen component in the near future or maybe is better for me to find the compatible orogen component on my own and install it from the source?

**Comment by 2maz** [comment]
Could you check which commit of simulation/orogen/mars is actually compatible.
Seeing similar build failures when trying to render the Debian package for simulation/orogen/mars, where HEAD is on 40cfe98.

**Comment by Rauldg** [comment]
@2maz The latest valid version of the simulation/orogen/mars is with HEAD on 19dc426.

**Comment by 2maz** [comment]
Added simultation/orogen/mars for amd64 and xenial,bionic,stretch: see 4d3e9f262982e898

**Comment by Rauldg** [comment]
As soon as I can run a test I will confirm if it is functional.
